/**
 * Groundwork — bilingual UI string dictionary (English / Arabic).
 * Every leaf is { en, ar }. Resolve with the `t()` helper from useLang().
 */

export interface Bi {
  en: string;
  ar: string;
}

export const ui = {
  brand: {
    tagline: { en: "Business Diagnostics", ar: "تشخيص الأعمال" },
  },

  nav: {
    method: { en: "Method", ar: "المنهجية" },
    diagnosis: { en: "Diagnosis", ar: "التشخيص" },
    problems: { en: "Problems", ar: "المشكلات" },
    tools: { en: "Tools", ar: "الأدوات" },
    actionPlan: { en: "Action Plan", ar: "خطة العمل" },
    cases: { en: "Cases", ar: "الحالات" },
    experts: { en: "Experts", ar: "الخبراء" },
    cta: { en: "Analyze My Business", ar: "حلِّل عملي" },
    openMenu: { en: "Open menu", ar: "فتح القائمة" },
    navigation: { en: "Navigation", ar: "التنقل" },
    mainNav: { en: "Main navigation", ar: "التنقل الرئيسي" },
    mobileNav: { en: "Mobile navigation", ar: "تنقل الجوال" },
    switchToAr: { en: "العربية", ar: "English" },
    langLabel: { en: "Switch to Arabic", ar: "التبديل إلى الإنجليزية" },
  },

  hero: {
    badge: {
      en: "Business diagnostics for small business — not motivational content",
      ar: "تشخيص أعمال للمنشآت الصغيرة — لا محتوى تحفيزي",
    },
    titleA: { en: "Turn business problems into", ar: "حوِّل مشكلات عملك إلى" },
    titleB: { en: "practical solutions.", ar: "حلول عملية." },
    sub: {
      en: "Understand what is holding your business back, identify the root cause, and build an actionable plan to improve it — sized for your money, your people, and your time.",
      ar: "افهم ما يعيق عملك فعليًا، وحدِّد السبب الجذري، وابنِ خطة قابلة للتنفيذ — على قدر مالك وفريقك ووقتك.",
    },
    ctaPrimary: { en: "Analyze My Business", ar: "حلِّل عملي" },
    ctaSecondary: { en: "Explore Business Problems", ar: "استكشف مشكلات الأعمال" },
    stat1v: { en: "10-step", ar: "10 خطوات" },
    stat1l: { en: "diagnostic method", ar: "منهجية تشخيص" },
    stat2l: { en: "business areas covered", ar: "مجال أعمال مغطى" },
    stat3v: { en: "12+", ar: "+12" },
    stat3l: { en: "problem patterns mapped", ar: "نمط مشكلات محلَّل" },
    fieldObs: { en: "Field observation · 07:40 AM", ar: "ملاحظة ميدانية · 07:40 صباحًا" },
    previewTitle: { en: "Diagnosis preview", ar: "معاينة التشخيص" },
    liveStructure: { en: "Live structure", ar: "هيكل حي" },
    ownerSees: { en: "What the owner sees", ar: "ما يراه صاحب العمل" },
    ownerQuote: {
      en: "“We’re busier than ever — but there’s nothing left at the end of the month.”",
      ar: "«أكثر انشغالًا من أي وقت مضى — لكن لا يتبقى شيء في نهاية الشهر.»",
    },
    symptomCause: { en: "Symptom → cause", ar: "العَرَض ← السبب" },
    likelyRoot: { en: "Likely root cause", ar: "السبب الجذري المرجَّح" },
    rootText: {
      en: "3 of the 10 best-selling products are priced below true cost. Growth concentrated volume exactly where margin is thinnest.",
      ar: "3 من أفضل 10 منتجات مبيعة مُسعَّرة دون كلفتها الحقيقية. النمو ركَّز الحجم تحديدًا حيث يكون الهامش الأدقّ.",
    },
    nowLabel: { en: "NOW", ar: "الآن" },
    nowText: { en: "Margin table", ar: "جدول الهوامش" },
    nextLabel: { en: "NEXT", ar: "التالي" },
    nextText: { en: "Reprice 9 items", ar: "إعادة تسعير 9 منتجات" },
    laterLabel: { en: "LATER", ar: "لاحقًا" },
    laterText: { en: "Value tiers", ar: "فئات القيمة" },
    kpiLine: {
      en: "KPI: gross margin 41% → 50%, reviewed weekly on a one-page scorecard.",
      ar: "مؤشر الأداء: هامش الربح الإجمالي من 41% إلى 50%، يُراجع أسبوعيًا في بطاقة من صفحة واحدة.",
    },
    factsNote: {
      en: "Facts, assumptions & to-verify kept separate",
      ar: "الوقائع والافتراضات وما يحتاج تحققًا تُعرض منفصلة",
    },
    builtFor: { en: "Built for real businesses", ar: "مبني لأعمال حقيقية" },
    realities: {
      shops: { en: "Shops", ar: "المتاجر" },
      workshops: { en: "Workshops", ar: "الورش" },
      restaurants: { en: "Restaurants", ar: "المطاعم" },
      retail: { en: "Retail stores", ar: "متاجر التجزئة" },
      services: { en: "Service businesses", ar: "الأعمال الخدمية" },
      trades: { en: "Trades", ar: "المهن الحرفية" },
      studios: { en: "Studios", ar: "الاستوديوهات" },
      suppliers: { en: "Local suppliers", ar: "الموردون المحليون" },
    },
  },

  method: {
    eyebrow: { en: "The diagnostic method", ar: "منهجية التشخيص" },
    title: { en: "Every problem gets the same disciplined process.", ar: "كل مشكلة تمر بالعملية المنضبطة ذاتها." },
    desc: {
      en: "No inspirational quotes, no one-size-fits-all playbooks. Just a structured method that separates what you see from what is actually broken — and compares real options before you spend anything.",
      ar: "لا اقتباسات ملهمة ولا وصفات جاهزة للجميع. منهجية منظمة تفصل بين ما تراه وما هو معطوب فعلًا — وتقارن الخيارات الحقيقية قبل أن تنفق أي شيء.",
    },
    phase: { en: "Phase", ar: "المرحلة" },
    refuse: { en: "What we refuse to do", ar: "ما نرفض فعله" },
    areasTitle: { en: "One connected system,", ar: "نظام واحد مترابط،" },
    areasTitleAccent: { en: "business areas", ar: "مجال أعمال" },
    areasNote: { en: "Problems rarely live in the area where they appear", ar: "المشكلات نادرًا ما تقيم في المجال الذي تظهر فيه" },
  },

  wizard: {
    eyebrow: { en: "Business diagnosis", ar: "تشخيص الأعمال" },
    title: { en: "What is the biggest problem in your business right now?", ar: "ما أكبر مشكلة في عملك الآن؟" },
    desc: {
      en: "Describe it in your own words. The diagnostic engine separates symptoms from root causes, compares real solution options, and returns a prioritized plan with KPIs — distinguishing what is known, assumed, and still needs verification.",
      ar: "صفها بكلماتك. محرك التشخيص يفصل الأعراض عن الأسباب الجذرية، ويقارن خيارات الحلول الحقيقية، ويعيد خطة مرتبة بالأولوية مع مؤشرات أداء — مميزًا بين ما هو معلوم، وما هو افتراض، وما يحتاج إلى تحقق.",
    },
    step1: { en: "Step 1 of 2 — Describe the situation", ar: "الخطوة 1 من 2 — صف الوضع" },
    step2: { en: "Step 2 of 2 — Three targeted questions", ar: "الخطوة 2 من 2 — ثلاثة أسئلة موجَّهة" },
    areaLabel: { en: "Which area feels most broken?", ar: "أي مجال يبدو الأكثر اختلالًا؟" },
    areaNote: {
      en: "Not sure? Pick your gut feeling — the diagnosis will test whether the problem actually lives there.",
      ar: "غير متأكد؟ اختر حدسك — التشخيص سيختبر إن كانت المشكلة تسكن هناك فعلًا.",
    },
    descLabel: { en: "What is happening in your business?", ar: "ما الذي يحدث في عملك؟" },
    descPlaceholder: {
      en: "e.g. We’re busier than ever — more customers, more orders — but at the end of the month there’s nothing left. I work 60+ hours and my own pay keeps shrinking. I don’t know if my prices are wrong or my costs are too high…",
      ar: "مثال: أكثر انشغالًا من أي وقت مضى — عملاء أكثر، طلبات أكثر — لكن في نهاية الشهر لا يتبقى شيء. أعمل أكثر من 60 ساعة أسبوعيًا وأجري الشخصي يتقلص. لا أدري هل أسعاري خاطئة أم تكاليفي مرتفعة…",
    },
    descHint: {
      en: "Facts, numbers and feelings all help. Write like you’d talk.",
      ar: "الوقائع والأرقام والمشاعر كلها تفيد. اكتب كما تتحدث.",
    },
    minChars: { en: "min", ar: "الأدنى" },
    nextHint: {
      en: "Next: 3 targeted questions — only the ones that can change the diagnosis.",
      ar: "التالي: 3 أسئلة موجَّهة — فقط ما قد يغيّر نتيجة التشخيص.",
    },
    continue: { en: "Continue", ar: "متابعة" },
    back: { en: "Back", ar: "رجوع" },
    run: { en: "Run Diagnosis", ar: "شغِّل التشخيص" },
    industryLabel: { en: "Business type (optional)", ar: "نوع النشاط (اختياري)" },
    industryPh: { en: "e.g. Bakery, plumbing, salon, consulting…", ar: "مثال: مخبز، سباكة، صالون، استشارات…" },
    sizeLabel: { en: "Team size (optional)", ar: "حجم الفريق (اختياري)" },
    sizePh: { en: "Select size", ar: "اختر الحجم" },
    sizes: {
      s1: { en: "Just me", ar: "أنا فقط" },
      s2: { en: "2-5 people", ar: "2-5 أشخاص" },
      s3: { en: "6-10 people", ar: "6-10 أشخاص" },
      s4: { en: "11-25 people", ar: "11-25 شخصًا" },
      s5: { en: "26-50 people", ar: "26-50 شخصًا" },
    },
    qPrefix: { en: "Q", ar: "س" },
    answerNote: {
      en: "Answer what you know, skip what you don’t — the engine works with incomplete information and flags what still needs verification.",
      ar: "أجب عما تعرفه وتجاوز ما لا تعرفه — المحرك يعمل بمعلومات ناقصة ويؤشّر على ما يحتاج إلى تحقق.",
    },
    analyzingTitle: { en: "Running your business diagnosis", ar: "جارٍ تشخيص عملك" },
    analyzingSub: {
      en: "Applying the 10-step method to your situation. This usually takes under a minute.",
      ar: "تطبيق منهجية الخطوات العشر على وضعك. يستغرق هذا عادة أقل من دقيقة.",
    },
    stages: {
      s1: { en: "Reading your description in full…", ar: "قراءة وصفك بالكامل…" },
      s2: { en: "Separating symptoms from root causes…", ar: "فصل الأعراض عن الأسباب الجذرية…" },
      s3: { en: "Tracing processes and dependencies…", ar: "تتبع العمليات والارتباطات…" },
      s4: { en: "Comparing solution options on cost, impact and risk…", ar: "مقارنة خيارات الحلول بالتكلفة والأثر والمخاطر…" },
      s5: { en: "Sequencing the implementation plan…", ar: "ترتيب خطة التنفيذ…" },
      s6: { en: "Defining KPIs and verification points…", ar: "تحديد مؤشرات الأداء ونقاط التحقق…" },
    },
    readyTitle: { en: "Your diagnosis is ready", ar: "تشخيصك جاهز" },
    readySub: {
      en: "Structured by the 10-step method · facts, assumptions and to-verify kept separate",
      ar: "منظم بمنهجية الخطوات العشر · الوقائع والافتراضات وما يحتاج تحققًا منفصلة",
    },
    generalBiz: { en: "General business", ar: "أعمال عامة" },
    errMin: {
      en: "Please describe what is happening in your business (at least a sentence).",
      ar: "يرجى وصف ما يحدث في عملك (جملة واحدة على الأقل).",
    },
    errFormat: {
      en: "The analysis returned an unexpected format. Please try again.",
      ar: "أعاد التحليل صيغة غير متوقعة. يرجى المحاولة مرة أخرى.",
    },
    errGeneric: { en: "Something went wrong. Please try again.", ar: "حدث خطأ ما. يرجى المحاولة مرة أخرى." },
    errToastTitle: { en: "Diagnosis could not complete", ar: "لم يكتمل التشخيص" },
    errEngine: {
      en: "The diagnostic engine could not complete the analysis. Please try again in a moment.",
      ar: "لم يتمكن محرك التشخيص من إكمال التحليل. يرجى المحاولة بعد قليل.",
    },
    errServer: {
      en: "Something went wrong while running the diagnosis. Please try again.",
      ar: "حدث خطأ أثناء تشغيل التشخيص. يرجى المحاولة مرة أخرى.",
    },
  },

  report: {
    problem: { en: "Problem — what is happening", ar: "المشكلة — ما الذي يحدث" },
    roots: { en: "Root causes — why it is happening", ar: "الأسباب الجذرية — لماذا يحدث" },
    impact: { en: "Business impact", ar: "الأثر على العمل" },
    facts: { en: "Known facts", ar: "وقائع معلومة" },
    assumptions: { en: "Assumptions", ar: "افتراضات" },
    toVerify: { en: "To verify", ar: "يحتاج تحققًا" },
    solutions: { en: "Solution options — compared", ar: "خيارات الحلول — مقارنة" },
    recommended: { en: "Recommended approach & reasoning", ar: "المقاربة الموصى بها ومنطقها" },
    firstMove: { en: "First move — next 48 hours", ar: "الخطوة الأولى — خلال 48 ساعة" },
    implementation: { en: "Implementation plan", ar: "خطة التنفيذ" },
    kpis: { en: "KPIs — how you’ll know it’s working", ar: "مؤشرات الأداء — كيف تعرف أنها تنجح" },
    risks: { en: "Risks — and how to reduce them", ar: "المخاطر — وكيف تقلّلها" },
    recBadge: { en: "Recommended path", ar: "المسار الموصى به" },
    impactL: { en: "Impact", ar: "الأثر" },
    costL: { en: "Cost", ar: "التكلفة" },
    complexityL: { en: "Complexity", ar: "التعقيد" },
    riskL: { en: "Risk", ar: "المخاطرة" },
    timeL: { en: "Time", ar: "المدة" },
    resourcesL: { en: "Resources", ar: "الموارد" },
    ownerL: { en: "Owner", ar: "المسؤول" },
    effortL: { en: "Effort", ar: "الجهد" },
    baselineL: { en: "Baseline", ar: "خط الأساس" },
    targetL: { en: "Target", ar: "الهدف" },
    mitigationL: { en: "Mitigation:", ar: "التخفيف:" },
    rerun: {
      en: "Re-run this diagnosis anytime — more context produces a sharper analysis.",
      ar: "أعد تشغيل التشخيص متى شئت — سياق أكثر يعني تحليلًا أدق.",
    },
    startOver: { en: "Start Over", ar: "البدء من جديد" },
    openTools: { en: "Open Business Tools", ar: "افتح أدوات الأعمال" },
    high: { en: "High", ar: "مرتفع" },
    medium: { en: "Medium", ar: "متوسط" },
    low: { en: "Low", ar: "منخفض" },
    likely: { en: "Likely", ar: "مرجَّح" },
    possible: { en: "Possible", ar: "ممكن" },
    needsVerif: { en: "Needs verification", ar: "يحتاج تحققًا" },
  },

  problems: {
    eyebrow: { en: "Problem library", ar: "مكتبة المشكلات" },
    title: { en: "Common problems, fully diagnosed.", ar: "مشكلات شائعة، مشخَّصة بالكامل." },
    desc: {
      en: "Twelve recurring small-business problems, each mapped from symptom to root causes to compared solutions, implementation steps, KPIs and risks. Recognize yours?",
      ar: "اثنتا عشرة مشكلة متكررة في الأعمال الصغيرة، كل منها مرسومة من العَرَض إلى الأسباب الجذرية إلى الحلول المقارنة وخطوات التنفيذ والمؤشرات والمخاطر. هل تجد مشكلتك؟",
    },
    all: { en: "All problems", ar: "كل المشكلات" },
    causesWord: { en: "causes", ar: "أسباب" },
    solsWord: { en: "solutions", ar: "حلول" },
    explore: { en: "Explore the solution", ar: "استكشف الحل" },
    pattern: { en: "Problem pattern", ar: "نمط المشكلة" },
    problem: { en: "Problem — what is happening", ar: "المشكلة — ما الذي يحدث" },
    roots: { en: "Root causes — why it happens", ar: "الأسباب الجذرية — لماذا تحدث" },
    impact: { en: "Business impact — what it costs you", ar: "الأثر على العمل — ماذا يكلفك" },
    solutions: { en: "Solution options — compare approaches", ar: "خيارات الحلول — قارن المقاربات" },
    recommended: { en: "Recommended approach & reasoning", ar: "المقاربة الموصى بها ومنطقها" },
    firstMove: { en: "First move — next 48 hours", ar: "الخطوة الأولى — خلال 48 ساعة" },
    implementation: { en: "Implementation plan", ar: "خطة التنفيذ" },
    kpis: { en: "KPIs", ar: "مؤشرات الأداء" },
    risks: { en: "Risks & mitigations", ar: "المخاطر والتخفيف" },
    mitigationL: { en: "Mitigation:", ar: "التخفيف:" },
    thisWeek: { en: "this week", ar: "هذا الأسبوع" },
    weeks26: { en: "2-6 weeks", ar: "2-6 أسابيع" },
    thisQuarter: { en: "this quarter", ar: "هذا الربع" },
    mostCommon: { en: "Most common", ar: "الأكثر شيوعًا" },
    frequent: { en: "Frequent", ar: "متكرر" },
    oftenHidden: { en: "Often hidden", ar: "غالبًا خفيّ" },
    possible: { en: "Possible", ar: "ممكن" },
  },

  tools: {
    eyebrow: { en: "Business tools", ar: "أدوات الأعمال" },
    title: { en: "Do the math before you decide.", ar: "احسبها قبل أن تقرر." },
    desc: {
      en: "Three working analyzers built for small-business numbers — no sign-up, no spreadsheet gymnastics. Each one answers a question that changes what you should do next.",
      ar: "ثلاثة محللات عملية مبنية لأرقام الأعمال الصغيرة — بلا تسجيل ولا بهرجة جداول. كل أداة تجيب عن سؤال يغيّر ما يجب فعله تاليًا.",
    },
    tabBreakEven: { en: "Break-Even", ar: "نقطة التعادل" },
    tabPricing: { en: "Pricing & Margin", ar: "التسعير والهامش" },
    tabCosts: { en: "Cost Structure", ar: "هيكل التكاليف" },
    privacy: {
      en: "All calculations run in your browser — nothing you type is stored or sent anywhere.",
      ar: "جميع الحسابات تعمل في متصفحك — لا يُخزَّن ما تكتبه ولا يُرسل إلى أي مكان.",
    },
    be: {
      price: { en: "Average price per sale", ar: "متوسط سعر البيع" },
      vcost: { en: "Variable cost per sale", ar: "التكلفة المتغيرة للبيع" },
      fixed: { en: "Monthly fixed costs", ar: "التكاليف الثابتة الشهرية" },
      vol: { en: "Current monthly volume", ar: "حجم المبيعات الشهري الحالي" },
      units: { en: "units", ar: "وحدة" },
      vcNote: {
        en: "Variable cost = anything that changes per sale: materials, delivery fees, payment processing, commissions.",
        ar: "التكلفة المتغيرة = كل ما يتغير مع كل عملية بيع: المواد، رسوم التوصيل، عمولات الدفع، العمولات.",
      },
      cm: { en: "Contribution / sale", ar: "المساهمة / بيع" },
      marginRatio: { en: "Margin ratio", ar: "نسبة الهامش" },
      breakEven: { en: "Break-even", ar: "نقطة التعادل" },
      sales: { en: "sales", ar: "عملية بيع" },
      perMonth: { en: "/ month", ar: "/ شهريًا" },
      belowCost: { en: "price below cost", ar: "السعر أدنى من التكلفة" },
      profit: { en: "Monthly profit", ar: "الربح الشهري" },
      safety: { en: "safety margin", ar: "هامش الأمان" },
      revenue: { en: "Revenue", ar: "الإيرادات" },
      totalCost: { en: "Total cost", ar: "التكلفة الإجمالية" },
      fixedCosts: { en: "Fixed costs", ar: "التكاليف الثابتة" },
      unitsSold: { en: "units sold", ar: "وحدة مبيعة" },
      emergency: { en: "Price is below variable cost", ar: "السعر أدنى من التكلفة المتغيرة" },
      emergencyA: { en: "Every sale loses", ar: "كل عملية بيع تخسر" },
      emergencyB: {
        en: "before fixed costs. This is a pricing emergency — selling more makes it worse.",
        ar: "قبل التكاليف الثابتة. هذه حالة طوارئ تسعير — البيع أكثر يجعلها أسوأ.",
      },
      howTo: {
        en: "How to read this:",
        ar: "كيف تقرأ هذا:",
      },
      howToBody: {
        en: "the blue line is revenue, the amber line is total cost. Where they cross is break-even. A margin ratio under 25% means pricing or variable costs deserve attention before anything else — including marketing.",
        ar: "الخط الأزرق هو الإيرادات، والخط الكهرماني هو التكلفة الإجمالية. نقطة تقاطعهما هي التعادل. نسبة هامش دون 25% تعني أن التسعير أو التكاليف المتغيرة تستحق الاهتمام قبل أي شيء آخر — بما في ذلك التسويق.",
      },
    },
    pr: {
      price: { en: "Current price", ar: "السعر الحالي" },
      cost: { en: "Cost per sale (materials + labor)", ar: "التكلفة للبيع (مواد + عمل)" },
      vol: { en: "Monthly volume", ar: "حجم المبيعات الشهري" },
      units: { en: "units", ar: "وحدة" },
      change: { en: "Price change", ar: "تغيير السعر" },
      newPrice: { en: "New price", ar: "السعر الجديد" },
      marginSale: { en: "Margin per sale", ar: "الهامش للبيع" },
      was: { en: "was", ar: "كان" },
      marginPct: { en: "Margin %", ar: "نسبة الهامش %" },
      gross: { en: "Monthly gross profit", ar: "إجمالي الربح الشهري" },
      vsToday: { en: "vs today", ar: "مقابل اليوم" },
      you: { en: "You", ar: "أنت" },
      profitLabel: { en: "Monthly gross profit", ar: "إجمالي الربح الشهري" },
      priceAt: { en: "Price", ar: "السعر" },
      caveat: { en: "Honest caveat:", ar: "تنبيه صريح:" },
      caveatBody: {
        en: "this model holds volume constant — real customers may buy less as prices rise. Use it to find your floor (the price where margin dies), then test a small rise (5-10%) on a few items first. The margin math tells you what a price change could win; only a real test tells you what it will win.",
        ar: "هذا النموذج يثبِّت الحجم — العملاء الحقيقيون قد يشترون أقل مع ارتفاع الأسعار. استخدمه لإيجاد أرضيتك (السعر الذي يموت عنده الهامش)، ثم جرِّب زيادة صغيرة (5-10%) على بعض المنتجات أولًا. حساب الهامش يخبرك بما قد تكسبه تغييرة السعر؛ الاختبار الحقيقي وحده يخبرك بما ستكسبه فعلًا.",
      },
    },
    cs: {
      revenue: { en: "Monthly revenue", ar: "الإيرادات الشهرية" },
      lines: { en: "Cost lines", ar: "بنود التكاليف" },
      add: { en: "Add line", ar: "إضافة بند" },
      namePh: { en: "Cost name", ar: "اسم البند" },
      amountAria: { en: "amount", ar: "المبلغ" },
      remove: { en: "Remove", ar: "حذف" },
      fix: { en: "Fix", ar: "ثابت" },
      var: { en: "Var", ar: "متغير" },
      fixed: { en: "Fixed costs", ar: "التكاليف الثابتة" },
      variable: { en: "Variable costs", ar: "التكاليف المتغيرة" },
      total: { en: "Total costs", ar: "إجمالي التكاليف" },
      ofRevenue: { en: "% of revenue", ar: "% من الإيرادات" },
      profit: { en: "Monthly profit", ar: "الربح الشهري" },
      margin: { en: "margin", ar: "الهامش" },
      unnamed: { en: "Unnamed", ar: "بند غير مسمى" },
      lookFor: { en: "What to look for:", ar: "ما الذي تبحث عنه:" },
      lookForA: { en: "your largest line is", ar: "أكبر بند لديك هو" },
      lookForB: { en: "of total costs", ar: "من إجمالي التكاليف" },
      lookForBody: {
        en: "Fixed costs above ~70% of revenue make a business fragile — every slow month hurts directly. And if you can’t name which costs are variable, that’s the first thing to fix.",
        ar: "التكاليف الثابتة فوق ~70% من الإيرادات تجعل العمل هشًّا — كل شهر بطيء يؤلم مباشرة. وإن لم تستطع تسمية أي التكاليف متغيرة، فهذا أول ما يجب إصلاحه.",
      },
      defaults: {
        rent: { en: "Rent & utilities", ar: "الإيجار والخدمات" },
        wages: { en: "Wages (base)", ar: "الأجور (الأساسية)" },
        materials: { en: "Materials / stock", ar: "المواد / المخزون" },
        software: { en: "Software & subscriptions", ar: "البرمجيات والاشتراكات" },
        delivery: { en: "Delivery & fuel", ar: "التوصيل والوقود" },
        marketing: { en: "Marketing", ar: "التسويق" },
      },
    },
  },

  plan: {
    eyebrow: { en: "Action plan", ar: "خطة العمل" },
    title: { en: "Every diagnosis ends in a sequenced roadmap.", ar: "كل تشخيص ينتهي بخارطة طريق مرتبة." },
    desc: {
      en: "Not a to-do dump — an ordered sequence. NOW actions produce information or release cash immediately. NEXT moves need that data first. LATER builds compounding structures. This is what a real plan looks like for one common diagnosis:",
      ar: "ليست قائمة مهام مبعثرة — بل تسلسل مرتب. إجراءات «الآن» تنتج معلومات أو تُطلق نقدًا فورًا. تحركات «التالي» تحتاج تلك البيانات أولًا. و«لاحقًا» يبني هياكل متراكمة الأثر. هكذا تبدو خطة حقيقية لتشخيص شائع:",
    },
    buildMy: { en: "Build my plan", ar: "ابنِ خطتي" },
    runMy: { en: "Run my diagnosis", ar: "شغِّل تشخيصي" },
    impactL: { en: "Impact:", ar: "الأثر:" },
    resourcesL: { en: "Resources:", ar: "الموارد:" },
    effortL: { en: "Effort:", ar: "الجهد:" },
    kpiL: { en: "KPI:", ar: "المؤشر:" },
    footer: {
      en: [
        "Every action carries its ",
        "why, expected impact, resources, effort and KPI",
        " — because a plan you can’t measure is just a wish with a deadline.",
      ],
      ar: [
        "كل إجراء يحمل ",
        "سببه وأثره المتوقع وموارده وجهده ومؤشره",
        " — لأن خطة لا يمكن قياسها ليست إلا أمنية بموعد نهائي.",
      ],
    } as { en: string[]; ar: string[] },
  },

  cases: {
    eyebrow: { en: "Case studies", ar: "دراسات حالة" },
    title: { en: "Real problems. Careful diagnoses. Honest results.", ar: "مشكلات حقيقية. تشخيصات متأنية. نتائج صادقة." },
    desc: {
      en: "No overnight successes — these are businesses that fixed systems over months, with numbers before and after. Each case follows the same arc: problem, diagnosis, intervention, result, lessons.",
      ar: "لا قصص نجاح ليلة واحدة — هذه أعمال أصلحت أنظمتها على مدى شهور، بأرقام قبل وبعد. كل حالة تسير القوس نفسه: المشكلة، التشخيص، التدخل، النتيجة، الدروس.",
    },
    problem: { en: "The problem", ar: "المشكلة" },
    diagnosis: { en: "The diagnosis", ar: "التشخيص" },
    intervention: { en: "The intervention", ar: "التدخل" },
    lessons: { en: "Lessons that transfer", ar: "دروس قابلة للنقل" },
    engagement: { en: "engagement", ar: "مدة الاشتباك" },
    cta: { en: "Diagnose my business", ar: "شخِّص عملي" },
  },

  experts: {
    eyebrow: { en: "The analysts", ar: "المحللون" },
    title: { en: "Expertise you can inspect, not just credentials.", ar: "خبرة يمكنك فحصها، لا مجرد شهادات." },
    desc: {
      en: "Every diagnosis and recommendation on this platform is grounded in the methods of practitioners who have spent years inside small businesses — food production floors, machine shops, retail counters, and back offices. Capability first; certificates second.",
      ar: "كل تشخيص وتوصية في هذه المنصة متجذرة في مناهج ممارسين أمضوا سنوات داخل الأعمال الصغيرة — أرضيات إنتاج الغذاء، الورش الميكانيكية، كاشيرات التجزئة، والمكاتب الخلفية. الكفاءة أولًا؛ الشهادات ثانيًا.",
    },
    verified: { en: "Verified practitioner", ar: "ممارس موثَّق" },
    method: { en: "Working method", ar: "منهج العمل" },
    footnote: {
      en: "Profiles represent the diagnostic disciplines behind the platform’s method — systems thinking, unit economics, cash-flow realism, and technology restraint.",
      ar: "تمثل الملفاتُ الانضباطياتِ التشخيصية الكامنة خلف منهجية المنصة — التفكير المنظومي، اقتصاديات الوحدة، واقعية التدفق النقدي، والتحفظ التقني.",
    },
  },

  cta: {
    titleA: { en: "Find the problem. ", ar: "اعثر على المشكلة. " },
    titleB: { en: "Build the solution.", ar: "ابنِ الحل." },
    titleC: { en: "Improve the business.", ar: "طوِّر العمل." },
    sub: {
      en: "Don’t settle for more generic advice. Understand your business, identify the real problem, and know exactly what to do next.",
      ar: "لا تكتفِ بمزيد من النصائح العامة. افهم عملك، وحدِّد المشكلة الحقيقية، واعرف بالضبط ما تفعله تاليًا.",
    },
    primary: { en: "Start Business Diagnosis", ar: "ابدأ تشخيص الأعمال" },
    secondary: { en: "Describe My Problem", ar: "صف مشكلتي" },
    note: {
      en: "Free · No sign-up · Runs in about a minute · Your inputs stay on your side",
      ar: "مجاني · بلا تسجيل · يستغرق نحو دقيقة · مدخلاتك تبقى عندك",
    },
  },

  footer: {
    desc: {
      en: "Tell us what is happening in your business. We help you understand the problem, find the cause, and build a practical solution — sized for small business money, people, and time.",
      ar: "أخبرنا بما يحدث في عملك. نساعدك على فهم المشكلة، والعثور على السبب، وبناء حل عملي — على قدر مال الأعمال الصغيرة وأشخاصها ووقتها.",
    },
    disclaimer: {
      en: "Groundwork provides business decision support, not financial, legal, or tax advice. Verify material decisions with a qualified professional.",
      ar: "تقدم المنصة دعمًا لقرارات الأعمال، لا استشارات مالية أو قانونية أو ضريبية. تحقق من القرارات الجوهرية لدى مهني مؤهل.",
    },
    platform: { en: "Platform", ar: "المنصة" },
    areas: { en: "Common areas", ar: "مجالات شائعة" },
    theMethod: { en: "The Method", ar: "المنهجية" },
    diagnosis: { en: "Business Diagnosis", ar: "تشخيص الأعمال" },
    library: { en: "Problem Library", ar: "مكتبة المشكلات" },
    tools: { en: "Business Tools", ar: "أدوات الأعمال" },
    plans: { en: "Action Plans", ar: "خطط العمل" },
    cases: { en: "Case Studies", ar: "دراسات الحالة" },
    areaLinks: {
      pricing: { en: "Pricing & margins", ar: "التسعير والهوامش" },
      cash: { en: "Cash flow", ar: "التدفق النقدي" },
      sales: { en: "Sales systems", ar: "أنظمة المبيعات" },
      retention: { en: "Customer retention", ar: "الاحتفاظ بالعملاء" },
      ops: { en: "Operations & process", ar: "العمليات والإجراءات" },
      ai: { en: "Automation & AI", ar: "الأتمتة والذكاء الاصطناعي" },
    },
    copyright: {
      en: "Groundwork — Business Diagnostics & Practical Solutions",
      ar: "جراوند ورك — تشخيص الأعمال وحلول عملية",
    },
    tagline: { en: "Systems, not symptoms.", ar: "أنظمة، لا أعراض." },
  },
} as const;

export type UI = typeof ui;
